# Generated by Django 2.2.3 on 2019-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbnprod',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mcbnprod',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mcbnprod',
            name='year',
            field=models.IntegerField(),
        ),
    ]
