# Generated by Django 2.2.3 on 2019-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190716_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbnprod',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mcbnprod',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mcbnprod',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
