# Generated by Django 2.2.3 on 2019-07-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190716_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbnprod',
            name='_class',
            field=models.CharField(db_column='class', max_length=255),
        ),
    ]
