from django.contrib.gis.db import models

# Create your models here.


class McbnProd(models.Model):
    typestatus = models.CharField(max_length=255)
    identificationqualifier = models.CharField(max_length=255)
    dateidentified = models.CharField(max_length=255)
    identifiedby = models.CharField(max_length=255)
    georeference_validated = models.CharField(max_length=255)
    year = models.IntegerField(null=True)
    month = models.IntegerField(null=True)
    day = models.IntegerField(null=True)
    maximumdepthinmeters = models.CharField(max_length=255)
    minimumdepthinmeters = models.CharField(max_length=255)
    maximumelevationinmeters = models.CharField(max_length=255)
    minimumelevationinmeters = models.CharField(max_length=255)
    individualcount = models.CharField(max_length=255)
    dayidentified = models.CharField(max_length=255)
    monthidentified = models.CharField(max_length=255)
    yearidentified = models.CharField(max_length=255)
    subspecies = models.CharField(max_length=255)
    species = models.CharField(max_length=255)
    domain = models.CharField(max_length=255)
    subspeciesid = models.CharField(max_length=255)
    speciesid = models.CharField(max_length=255)
    genusid = models.CharField(max_length=255)
    familyid = models.CharField(max_length=255)
    taxonrank = models.CharField(max_length=255)
    scientificnameauthorship = models.CharField(max_length=255)
    infraspecificepithet = models.CharField(max_length=255)
    specificepithet = models.CharField(max_length=255)
    subgenus = models.CharField(max_length=255)
    genus = models.CharField(max_length=255)
    family = models.CharField(max_length=255)
    _order = models.CharField(max_length=255)
    _class = models.CharField(max_length=255)
    phylum = models.CharField(max_length=255)
    kingdom = models.CharField(max_length=255)
    scientificname = models.CharField(max_length=255)
    geodeticdatum = models.CharField(max_length=255)
    islandgroup = models.CharField(max_length=255)
    island = models.CharField(max_length=255)
    waterbody = models.CharField(max_length=255)
    verbatimlocality = models.CharField(max_length=255)
    locality = models.CharField(max_length=255)
    municipality = models.CharField(max_length=255)
    county = models.CharField(max_length=255)
    stateprovince = models.CharField(max_length=255)
    countrycode = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    continent = models.CharField(max_length=255)
    eventremarks = models.CharField(max_length=255)
    samplingprotocol = models.CharField(max_length=255)
    habitat = models.CharField(max_length=255)
    verbatimeventdate = models.CharField(max_length=255)
    eventdate = models.CharField(max_length=255)
    fieldnumber = models.CharField(max_length=255)
    occurrenceid = models.CharField(max_length=255)
    previousidentifications = models.CharField(max_length=255)
    associatedoccurrences = models.CharField(max_length=255)
    othercatalognumbers = models.CharField(max_length=255)
    associatedreferences = models.CharField(max_length=255)
    preparations = models.CharField(max_length=255)
    lifestage = models.CharField(max_length=255)
    sex = models.CharField(max_length=255)
    recordedby = models.CharField(max_length=255)
    recordnumber = models.CharField(max_length=255)
    catalognumber = models.CharField(max_length=255)
    basisofrecord = models.CharField(max_length=255)
    collectioncode = models.CharField(max_length=255)
    institutioncode = models.CharField(max_length=255)
    coordinateuncertaintyinmeters = models.CharField(max_length=255)
    decimallongitude = models.DecimalField(max_digits=19, decimal_places=10)
    decimallatitude = models.DecimalField(max_digits=19, decimal_places=10)
    geom = models.PointField()
